# Generated by Django 4.0.2 on 2022-07-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfCity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Data_charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr_id', models.IntegerField(default=0, verbose_name='id_Username')),
                ('age', models.IntegerField(verbose_name='age')),
                ('cityLiveIn', models.IntegerField(verbose_name='city live in')),
                ('gender', models.CharField(max_length=1, verbose_name='gender')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('hour_of_debit', models.TimeField(verbose_name='hour_of_debit')),
                ('time_of_debit', models.IntegerField(verbose_name='time_of_debit')),
                ('city_of_debit', models.IntegerField(verbose_name='city_of_debit')),
                ('credit_card_showed', models.BinaryField(verbose_name='credit_card_showed')),
                ('is_fraud', models.BinaryField(verbose_name='is_fraud')),
            ],
        ),
    ]
