# Generated by Django 4.0.2 on 2022-07-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_charge',
            name='Gender',
            field=models.CharField(default=None, max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='age',
            field=models.IntegerField(default=None, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='amount',
            field=models.IntegerField(default=None, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='cityLiveIn',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='city live in'),
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='city_of_debit',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='city_of_debit'),
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='credit_card_showed',
            field=models.BinaryField(default=None, null=True, verbose_name='credit_card_showed'),
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='hour_of_debit',
            field=models.DateField(default=None, null=True, verbose_name='hour_of_debit'),
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='id_Username',
            field=models.IntegerField(default=0, null=True, verbose_name='id_Username'),
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='is_fraud',
            field=models.BinaryField(default=None, null=True, verbose_name='is_fraud'),
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='time_of_debit',
            field=models.IntegerField(default=None, null=True, verbose_name='time_of_debit'),
        ),
    ]
