# Generated by Django 4.0.2 on 2022-07-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetection', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_charge',
            old_name='usr_id',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='is_fraud',
            field=models.BinaryField(default=0, verbose_name='is_fraud'),
        ),
    ]
