# Generated by Django 4.0.2 on 2022-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetection', '0002_alter_data_charge_gender_alter_data_charge_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_charge',
            name='hour_of_debit',
            field=models.TimeField(default=None, null=True, verbose_name='hour_of_debit'),
        ),
    ]
