# Generated by Django 4.0.2 on 2022-07-27 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetection', '0002_rename_usr_id_data_charge_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_charge',
            name='month_of_debit',
        ),
        migrations.RemoveField(
            model_name='data_charge',
            name='year_of_debit',
        ),
        migrations.AddField(
            model_name='data_charge',
            name='date_of_debit',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='time_of_debit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data_charge',
            name='day_of_debit',
            field=models.IntegerField(verbose_name='date_of_debit'),
        ),
    ]
