# Generated by Django 4.0.2 on 2022-07-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetection', '0003_alter_data_charge_hour_of_debit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_charge',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='data_charge',
            old_name='id_Username',
            new_name='usr_id',
        ),
    ]
