# Generated by Django 4.0.2 on 2022-07-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frauddetection', '0004_rename_gender_data_charge_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfCity', models.CharField(max_length=30)),
            ],
        ),
    ]
