# Generated by Django 4.0.2 on 2022-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_join', models.DateField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('birth', models.DateField(verbose_name='birth')),
                ('age', models.IntegerField(default=1, null=True, verbose_name='age')),
                ('cityLiveIn', models.CharField(max_length=30, verbose_name='city live in')),
                ('gender', models.CharField(max_length=1, verbose_name='gender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
