# Generated by Django 4.0.2 on 2022-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='brith',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(null=True, verbose_name='birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_join',
            field=models.DateField(auto_now_add=True, verbose_name='date joined'),
        ),
    ]
